# Generated by Django 5.1.7 on 2025-03-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ciudad',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='comuna',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
