# Generated by Django 5.1.7 on 2025-03-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_usuarios_ciudad_usuarios_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='ciudad',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
