# Generated by Django 5.1.7 on 2025-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('procesador', models.CharField(max_length=50)),
                ('memoria_ram', models.CharField(max_length=20)),
                ('almacenamiento', models.CharField(max_length=20)),
                ('tarjeta_grafica', models.CharField(blank=True, max_length=50)),
                ('pantalla', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=20)),
                ('autonomia_bateria', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('procesador', models.CharField(max_length=50)),
                ('memoria_ram', models.CharField(max_length=20)),
                ('almacenamiento', models.CharField(max_length=20)),
                ('tarjeta_grafica', models.CharField(max_length=50)),
                ('fuente_poder', models.CharField(max_length=50)),
                ('gabinete', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('incluye_monitor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('pantalla', models.CharField(max_length=50)),
                ('camara_principal', models.CharField(max_length=50)),
                ('camara_frontal', models.CharField(max_length=50)),
                ('bateria', models.CharField(max_length=50)),
                ('memoria_ram', models.CharField(max_length=20)),
                ('almacenamiento', models.CharField(max_length=20)),
                ('dual_sim', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('pantalla', models.CharField(max_length=50)),
                ('memoria_ram', models.CharField(max_length=20)),
                ('almacenamiento', models.CharField(max_length=20)),
                ('camara_frontal', models.CharField(max_length=50)),
                ('camara_trasera', models.CharField(max_length=50)),
                ('conectividad', models.CharField(max_length=50)),
                ('stylus_incluido', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('tipo_pantalla', models.CharField(max_length=50)),
                ('resolucion', models.CharField(max_length=50)),
                ('tamaño_pantalla', models.CharField(max_length=20)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('smart_tv', models.BooleanField(default=True)),
                ('puertos_hdmi', models.PositiveIntegerField()),
                ('puertos_usb', models.PositiveIntegerField()),
                ('conectividad', models.CharField(max_length=100)),
                ('sonido', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
