# Generated by Django 5.1.7 on 2025-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='tipo',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores'), ('pc escritorio', 'PC Escritorio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pcescritorio',
            name='tipo',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores'), ('pc escritorio', 'PC Escritorio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='tipo',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores'), ('pc escritorio', 'PC Escritorio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='tipo',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores'), ('pc escritorio', 'PC Escritorio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='tipo',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('televisores', 'Televisores'), ('pc escritorio', 'PC Escritorio')], max_length=50),
        ),
    ]
